### ISSUE TITLE
Message to long

### ISSUE THREAD

**Issue by Tooom84** [xtrp/discord-vc-notifier#2]
If many members have signed up for a notification, you can no longer see the text which member is joint. Is it possible to mention the members (@user, @ user1, @ user2 ...) at the end of the join notification?

**Comment by xtrp** [comment]
Thanks for submitting the issue; this is something that I've been thinking of doing for some time. I'll go ahead and see if I can add that functionality in the next couple of business days.

— Gabriel

**Comment by xtrp** [comment]
This updated code will be pushed within the next couple of days.
